# Backend playbook
---
- hosts: backend
  become: True
  become_method: sudo

  roles:
    - lesmyrmidons.mongodb
    - geerlingguy.nodejs
  
  tasks:
    - name: APT Packages updated
      apt: update_cache=yes upgrade=dist

    - name: Scraper APT dependencies installed
      apt: name={{item}} state=installed
      with_items:
        - build-essential
        - libssl-dev
        - python-dev
        - python-pip
        - redis-server

    - name: Scraper Python dependencies installed
      pip: requirements=/vagrant/scraper/requirements.txt
